import { applyMixins } from '../utils'
import { JdUnionBase } from './api-base'
import {
  QueryMatchBonusActivityAPI,
  QueryMultimatchBonusActivityAPI,
  QueryBonusActivityAPI,
  QueryActivityAPI,
  QueryRecommendActivityAPI,
  GetGoodsCategoryAPI,
  GetInvitecodeChannelAPI,
  GetRelationChannelAPI,
  QueryRelationChannelAPI,
  GetGiftCouponAPI,
  StopGiftCouponAPI,
  QueryCouponAPI,
  QueryBigfieldGoodsAPI,
  QueryCombinationGoodsAPI,
  QueryJingfenGoodsAPI,
  QueryMaterialGoodsAPI,
  QueryGoodsAPI,
  QueryAgentOrderAPI,
  QueryBonusOrderAPI,
  QueryRowOrderAPI,
  QuerySupplyRowOrderAPI,
  CreatePositionAPI,
  QueryPositionAPI,
  GetBysubunionidPromotionAPI,
  GetByunionidPromotionAPI,
  GetCommonPromotionAPI,
  QueryIntelligencePromotionAPI,
  QueryIntelligenceToolsPromotionAPI,
  QueryGoodsSellingAPI,
  QueryRowOrderSellingAPI,
  GetPromotionSellingAPI,
  QueryBonusActivityStatisticsAPI,
  QueryGiftcouponStatisticsAPI,
  QueryPromotionStatisticsAPI,
  QueryAgentRedpacketStatisticsAPI,
  QueryRedpacketStatisticsAPI,
  GetPidUserAPI,
  ValidateRegisterUserAPI
} from './module'

export interface JdUnionAPI
  extends JdUnionBase,
    QueryMatchBonusActivityAPI,
    QueryMultimatchBonusActivityAPI,
    QueryBonusActivityAPI,
    QueryActivityAPI,
    QueryRecommendActivityAPI,
    GetGoodsCategoryAPI,
    GetInvitecodeChannelAPI,
    GetRelationChannelAPI,
    QueryRelationChannelAPI,
    GetGiftCouponAPI,
    StopGiftCouponAPI,
    QueryCouponAPI,
    QueryBigfieldGoodsAPI,
    QueryCombinationGoodsAPI,
    QueryJingfenGoodsAPI,
    QueryMaterialGoodsAPI,
    QueryGoodsAPI,
    QueryAgentOrderAPI,
    QueryBonusOrderAPI,
    QueryRowOrderAPI,
    QuerySupplyRowOrderAPI,
    CreatePositionAPI,
    QueryPositionAPI,
    GetBysubunionidPromotionAPI,
    GetByunionidPromotionAPI,
    GetCommonPromotionAPI,
    QueryIntelligencePromotionAPI,
    QueryIntelligenceToolsPromotionAPI,
    QueryGoodsSellingAPI,
    QueryRowOrderSellingAPI,
    GetPromotionSellingAPI,
    QueryBonusActivityStatisticsAPI,
    QueryGiftcouponStatisticsAPI,
    QueryPromotionStatisticsAPI,
    QueryAgentRedpacketStatisticsAPI,
    QueryRedpacketStatisticsAPI,
    GetPidUserAPI,
    ValidateRegisterUserAPI {}

export class JdUnionAPI extends JdUnionBase {
  constructor(options: { appKey: string; secretKey: string }) {
    super(options)
  }
}

applyMixins(JdUnionAPI, [
  QueryMatchBonusActivityAPI,
  QueryMultimatchBonusActivityAPI,
  QueryBonusActivityAPI,
  QueryActivityAPI,
  QueryRecommendActivityAPI,
  GetGoodsCategoryAPI,
  GetInvitecodeChannelAPI,
  GetRelationChannelAPI,
  QueryRelationChannelAPI,
  GetGiftCouponAPI,
  StopGiftCouponAPI,
  QueryCouponAPI,
  QueryBigfieldGoodsAPI,
  QueryCombinationGoodsAPI,
  QueryJingfenGoodsAPI,
  QueryMaterialGoodsAPI,
  QueryGoodsAPI,
  QueryAgentOrderAPI,
  QueryBonusOrderAPI,
  QueryRowOrderAPI,
  QuerySupplyRowOrderAPI,
  CreatePositionAPI,
  QueryPositionAPI,
  GetBysubunionidPromotionAPI,
  GetByunionidPromotionAPI,
  GetCommonPromotionAPI,
  QueryIntelligencePromotionAPI,
  QueryIntelligenceToolsPromotionAPI,
  QueryGoodsSellingAPI,
  QueryRowOrderSellingAPI,
  GetPromotionSellingAPI,
  QueryBonusActivityStatisticsAPI,
  QueryGiftcouponStatisticsAPI,
  QueryPromotionStatisticsAPI,
  QueryAgentRedpacketStatisticsAPI,
  QueryRedpacketStatisticsAPI,
  GetPidUserAPI,
  ValidateRegisterUserAPI
])

export * from './module'
